name: Release-$(rev:r)

pool:
  name: RSConnect

trigger:
  branches:
    include:
    - main
  paths:
    exclude:
    - azure-pipelines.yml

resources:
  repositories:
    - repository: posit-deploy
      type: git
      name: ESFA-Data-Science/posit-deploy

extends:
  template: deploy.yml@posit-deploy
  parameters:
    appName: Shiny-App
    environments:
    - name: Pre-Production
      appId: none
    - name: Production
      appId: none
    approvers: |
      emily.yau@education.gov.uk
      richard.bielby@education.gov.uk
      cameron.race@education.gov.uk
      jen.machin@education.gov.uk
      charlotte.foster@education.gov.uk
