on:
  push:
    branches:
      - main
  
  pull_request:
      
name: tidy-code

jobs:
  automatedTests:
    runs-on: ubuntu-latest
    
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4
     
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
          
      - name: Install git2r dependencies
        run: sudo apt-get install -y libgit2-dev
        
      - name: Install curl dependencies
        run: sudo apt-get install libcurl4-openssl-dev
        
    
      - name: Install fontconfig and harfbuzz dependencies
        run: |
            sudo apt-get update
            sudo apt-get install -y libfontconfig1-dev libharfbuzz-dev

      - name: Set PKG_CONFIG_PATH
        run: echo "PKG_CONFIG_PATH=/usr/lib/x86_64-linux-gnu/pkgconfig" >> $GITHUB_ENV

      - uses: r-lib/actions/setup-renv@v2
          
      - name: Tidy code
        shell: Rscript {0}
        run: |
            codeChecks <- dfeshiny::tidy_code()
            
            if(any(is.na(codeChecks))) {
              stop("There is a breaking error in the code.")
            } else {
              if(TRUE %in% codeChecks) {
                stop("The code is not styled correctly. Open the project in RStudio and use tidy_code() to restyle the code.")
              } else {
                message("----------------------------------------")
                message("The code is beautiful, go you!")
                message("----------------------------------------")
              }
            }

      - name: Upload test results
        if: failure()
        uses: actions/upload-artifact@master
        with:
          name: ${{ runner.os }}-r${{ matrix.config.r }}-tests
          path: tests
